export const config = {
  port: Number(process.env.PORT || process.env.MALACHI_PORT || 8787),
  timezone: process.env.MALACHI_TIMEZONE || 'Asia/Jerusalem',
  publicBaseUrl: process.env.MALACHI_PUBLIC_BASE_URL || 'http://localhost:8787',
  schedulerEnabled: process.env.MALACHI_SCHEDULER !== 'false',
  schedulerIntervalMs: Number(process.env.MALACHI_SCHEDULER_INTERVAL_MS || 60000),
  selfKeepaliveEnabled: process.env.MALACHI_SELF_KEEPALIVE === 'true',
  selfKeepaliveIntervalMs: Number(process.env.MALACHI_SELF_KEEPALIVE_INTERVAL_MS || 240000),
  noResponseGraceMinutes: Number(process.env.MALACHI_NO_RESPONSE_GRACE_MINUTES || 30),
  reminderIntervalMinutes: Number(process.env.MALACHI_REMINDER_INTERVAL_MINUTES || process.env.MALACHI_NO_RESPONSE_GRACE_MINUTES || 30),
  reminderAttemptCount: Number(process.env.MALACHI_REMINDER_ATTEMPT_COUNT || 3),
  betaOpen: process.env.MALACHI_BETA_OPEN !== 'false',
  betaMaxFamilies: Number(process.env.MALACHI_BETA_MAX_FAMILIES || 50),
  firebaseAuthEnabled: process.env.FIREBASE_AUTH_ENABLED === 'true',
  feedbackNotifyWebhook: process.env.MALACHI_FEEDBACK_NOTIFY_WEBHOOK || '',
  adminToken: process.env.MALACHI_ADMIN_TOKEN || '',
  websiteLeadAutoReplyEnabled: process.env.MALACHI_WEBSITE_LEAD_AUTO_REPLY !== 'false',
  websiteLeadMatchText: process.env.MALACHI_WEBSITE_LEAD_MATCH_TEXT || 'הגעתי דרך אתר מלאכי',
  websiteLeadAutoReplyText: process.env.MALACHI_WEBSITE_LEAD_AUTO_REPLY_TEXT || 'היי 👋 תודה שפנית למלאכי.\nהפנייה שלך התקבלה.\nאפשר לכתוב כאן בקצרה במה נוכל לעזור, ומלאכי יחזור אליך בהקדם.',
  devToolsEnabled: process.env.MALACHI_DEV_TOOLS === 'true' || process.env.NODE_ENV !== 'production',
  whatsappProvider: process.env.WHATSAPP_PROVIDER || 'mock',
  dailyCheckMode: process.env.MALACHI_DAILY_CHECK_MODE || 'single_ok',
  hodayaAgent: {
    enabled: process.env.HODAYA_AGENT_ENABLED === 'true',
    phone: process.env.HODAYA_AGENT_PHONE || '',
    displayName: process.env.HODAYA_AGENT_DISPLAY_NAME || 'הודיה',
    windowTemplate: process.env.HODAYA_AGENT_WINDOW_TEMPLATE || process.env.META_TEMPLATE_HODAYA_WINDOW_OPEN || '',
    eventDrivenEnabled: process.env.HODAYA_AGENT_EVENT_DRIVEN === 'true',
    eventHookUrl: process.env.HODAYA_AGENT_EVENT_HOOK_URL || '',
    eventHookToken: process.env.HODAYA_AGENT_EVENT_HOOK_TOKEN || '',
    eventDebounceMs: Math.min(Number(process.env.HODAYA_AGENT_EVENT_DEBOUNCE_MS || 300), 300),
    eventRateLimitMs: Math.min(Number(process.env.HODAYA_AGENT_EVENT_RATE_LIMIT_MS || 1000), 1000),
    eventHookTimeoutMs: Number(process.env.HODAYA_AGENT_EVENT_HOOK_TIMEOUT_MS || 10000),
    typingIndicatorEnabled: process.env.HODAYA_AGENT_TYPING_INDICATOR !== 'false',
    fastAckEnabled: process.env.HODAYA_AGENT_FAST_ACK === 'force_true',
    fastAckMinGapMs: Number(process.env.HODAYA_AGENT_FAST_ACK_MIN_GAP_MS || 15000)
  },
  meta: {
    graphVersion: process.env.META_GRAPH_VERSION || 'v23.0',
    wabaId: process.env.META_WABA_ID || '',
    phoneNumberId: process.env.META_PHONE_NUMBER_ID || '',
    accessToken: process.env.META_ACCESS_TOKEN || '',
    verifyToken: process.env.META_VERIFY_TOKEN || (process.env.NODE_ENV === 'production' ? '' : 'change-me'),
    templates: {
      dailyCheck: process.env.META_TEMPLATE_DAILY_CHECK || 'daily_check_he',
      dailyReminder: process.env.META_TEMPLATE_DAILY_REMINDER || 'daily_check_reminder_he',
      okAck: process.env.META_TEMPLATE_OK_ACK || 'daily_ok_ack_he',
      incompleteSignupReminder: process.env.META_TEMPLATE_INCOMPLETE_SIGNUP_REMINDER || 'incomplete_signup_reminder_he',
      distressAlert: process.env.META_TEMPLATE_DISTRESS_ALERT || 'distress_alert_he',
      noResponseAlert: process.env.META_TEMPLATE_NO_RESPONSE_ALERT || 'no_response_alert_he',
      familyGreeting: process.env.META_TEMPLATE_FAMILY_GREETING || 'family_greeting_message_he',
      optin: process.env.META_TEMPLATE_OPTIN || 'contact_optin_he',
      contactOptin: process.env.META_TEMPLATE_CONTACT_OPTIN || process.env.META_TEMPLATE_OPTIN || 'optin_confirm_he'
    }
  }
};
